const projectData = [
    {
      id: 1,
      title: "Audio Bid",
      description: "AudioBid is a Django-based voice transcription job portal with dynamic pricing and Google OAuth integration. It offers multiple audio upload options and utilizes AWS S3 for storage and streaming. The platform enables users to claim and get paid for jobs, along with a chat system for seamless communication.",
      image: require("../assets/AudioBidProject.png"),
      demoLink: "https://audiobid.herokuapp.com/",
      githubLink: "https://github.com/vasunverma/binary-classification-high-dim-data",
      tags: ["Python", "Django", "JavaScript", "S3", "PostgreSQL", "SES", "OAuth", "HTML/CSS", "Heroku"],
      tagColor: ["blue", "red", "yellow", "orange", "teal", "green", "purple", "pink", "red"],
      rowSpan: 1,
      columnSpan: 2,
    },
    {
      id: 2,
      title: "Binary Classification with High-Dimensional Data",
      description: "Binary classification models were developed using R, Caret, Baruta, XgBoost, Tensorflow, Keras, and RandomForest for binary classification with high-dimensional data. Predictor reduction techniques were applied, achieving 20 predictors while maintaining high predictive power. Rigorous cross-validation techniques led to 82% accuracy on the validation set, accompanied by insightful visualizations and statistical summaries.",
      image: require("../assets/BinaryClassificationProject.png"),
      githubLink: "https://github.com/vasunverma/binary-classification-high-dim-data",
      tags: ["R", "XgBoost", "Baruta", "Tensorflow", "PCA", "Keras", "RandomForest", "Caret"],
      tagColor: ["blue", "red", "yellow", "orange", "teal", "green", "purple", "pink"],
      rowSpan: 1,
      columnSpan: 2,
    },
    {
      id: 3,
      title: "Smart Air Purifier",
      description: "A budget-friendly smart air purifier was designed and developed using C++, Arduino, AWS IoT, HTML/CSS, JavaScript, and P5.js. The purifier integrated dust, temperature, and humidity sensors to provide real-time air quality feedback. It featured an automatic switch-on function triggered by high dust density and utilized MQTT protocol for real-time communication with the web app. The purifier effectively cleaned indoor air using HEPA H13 and activated carbon filters.",
      image: require("../assets/SmartAirPurifierProject.jpg"),
      githubLink: "https://github.com/vasunverma/binary-classification-high-dim-data",
      tags: ["C++", "Arduino", "AWS IoT", "JavaScript", "HTML/CSS", "P5.js", "MQTT"],
      tagColor: ["blue", "red", "yellow", "orange", "teal", "green", "purple"],
      rowSpan: 1,
      columnSpan: 2,
    },
    {
        id: 4,
        title: "Timer App",
        description: "Timer App is a sleek and user-friendly desktop application developed with Electron.js, providing a seamless and customizable timer experience for various purposes.",
        // image: require("../assets/SmartAirPurifierProject.jpg"),
        githubLink: "https://github.com/vasunverma/Timer-App",
        tags: ["Electron", "Javascript", "HTML", "CSS"],
        tagColor: ["orange", "teal", "green", "purple"],
        rowSpan: 1,
        columnSpan: 1,
    },
    {
        id: 5,
        title: "URL Shortener",
        description: "URL Shortener is a web application developed using Flask, HTML, and CSS. It enables users to shorten long URLs and provides a convenient way to share them.",
        // image: require("../assets/SmartAirPurifierProject.jpg"),
        githubLink: "https://github.com/vasunverma/URL-Shortner",
        tags: ["Flask", "Python", "Javascript", "HTML", "CSS"],
        tagColor: ["blue", "red", "yellow", "orange", "teal"],
        rowSpan: 1,
        columnSpan: 1,
    }
  ];
  
  export default projectData;
  